### ISSUE TITLE
Move or fork to fortran-lang?

### ISSUE THREAD

**Issue by rouson** [awvwgk/homebrew-fpm#15]
@awvwgk would it make sense to move or fork this repository to the [fortran-lang](https:github.com/fortran-lang/)?  I'm now tapping this formula in an [installation script](https://github.com/BerkeleyLab/caffeine/blob/main/install.sh#L224) and it might be nice to place the formula somewhere that could encourage community support and adoption.

**Comment by awvwgk** [comment]
If there is interest I can transfer this repository to @fortran-lang. The alternative is to create a new repo (maybe `fortran-lang/homebrew-fortran`) and move the formulas over one by committing them again (since some are already in `homebrew-core`) and afterwards archive this repo.

cc @certik @milancurcic @lkedward

**Comment by milancurcic** [comment]
Hi @rouson @awvwgk, either approach proposed by Sebastian sounds good to me.

**Comment by certik** [comment]
That's fine with me.

**Comment by awvwgk** [comment]
I created https://github.com/fortran-lang/homebrew-fortran and also open PRs for the fpm and LFortran formulas.

**Comment by awvwgk** [comment]
Feel free to try it out. Once the CI passes add the `pr-pull` label to the PR and wait for the automatic merge to happen and upload the packages.
